### PR TITLE
Update links to organizing the Microcks repository in documentation

### LINKED ISSUE #73: Links to "organizing the Microcks repository" leads to old ui view
### Describe the bug

"organizing repository" leads to https://microcks.io/documentation/using/advanced/organizing/

### Attach any resources that can help us understand the issue.

_No response_

### PR DESCRIPTION
**Pull request by soGit**
Update links to "organizing repository" in documentation to latest ui

### Description

Updated pages:

1. Administrating
- users
2. Using
- asyncapi
- metadata
- openapi
- tests

### Related issue(s)

Fix #73

### CODE REVIEW

**Comment by yada** [comment]
Thanks @soGit for the fix.
LGTM

**Comment by yada** [comment]
Let's take the opportunity to dig further open questions before we merge this one:

1. content/documentation/administrating/users.md may be linked to https://microcks.io/documentation/using/organizing/ ?
2. maybe we should use an absolute path for all instead of a relative one to avoid link issues...

**Comment by soGit** [comment]
> 1. https://microcks.io/documentation/using/organizing/

1. I have verified that no more broken links to https://microcks.io/documentation/using/organizing/
2. I don't think that absolute path is better for avoiding broken links issues.

I can try to update CI/CD to include links verification.

**Review by lbroudoux — APPROVED** [review]
Thanks for fixing the broker links!

**Comment by yada** [comment]
Yep link verification using GitHub action will help +1

**Pull request merged**
