### PR TITLE
doc: add Service Account configuration for cli usage

### PR DESCRIPTION
**Pull request by Damounet**
### Description

Add a bit of information to configure properly a service account for cli usage.

### Related issue(s)

Following a discussion on Discord about the matter : https://discord.com/channels/1162356525969449100/1197840257073295471

### CODE REVIEW

**Review by lbroudoux — APPROVED** [review]
LGTM! Thank you!

**Comment by lbroudoux** [comment]
Hey @Damounet!

Thank you for the contrib! The other checks are not important but could you at least fix the DCO stuff?

If you've made things through the GitHub UI, you must clone your branch on your machine and then apply the recommended command.

Something like:
```bash
git clone https://github.com/Damounet/microcks.io/ && cd microcks.io
git switch patch-1
git rebase HEAD~1 --signoff
git push --force-with-lease origin patch-1
```

Signing commits is a prerequisites for CNCF projects.

Thanks!

**Comment by Damounet** [comment]
Done and dusted

**Comment by lbroudoux** [comment]
Thank you!

**Pull request merged**
