### PR TITLE
docs: Reviewing the getting started guide with microcks hub usage

### PR DESCRIPTION
**Pull request by kengneruphine**
### Description

- Adding steps on how to load samples from the Microcks Hub into the Microcks platform and changed the images as well
- Reviewed the steps under the Getting Started with Testing page and changed the images as well

### Related issue(s)
Related to issue[ #852](https://github.com/microcks/microcks/issues/852)

### CODE REVIEW

**Comment by lbroudoux** [comment]
Hi @kengneruphine! I4m just back from some days off, I will have a look at it as soon as possible! Thanks!

**Review by lbroudoux — APPROVED** [review]
LGTM with some minor fixes. Thanks a lot for this contribution!

**Comment by lbroudoux** [comment]
Hey @kengneruphine! Thanks a lot for your patience! We finally found some time to review it after this long delay...
It's now merged and already online on the website. Looking for froward to reviewing your next PR and this time we'll do our best to be more reactive 😉

**Comment by kengneruphine** [comment]
Hello @lbroudoux ,Thank you for reviewing and merging this PR

**Pull request merged**
