### PR TITLE
feat: Replace "Twitter" icon with "X" icon in footer

### LINKED ISSUE #233: Replace twitter by X in web page footer (icons)
### Reason/Context

Replace "Twitter" with "X" to reflect the platform's rebranding. This change ensures consistency and accuracy in how we refer to social media channels, keeping our content up to date with the latest industry changes.

### Description

Just change and replace the footer icon.

### Implementation ideas

See if an X icon exists for the footer:
X

### PR DESCRIPTION
**Pull request by ericklasluisa**
### Description

- Updated the `go.mod` and `go.sum` files using the command `hugo mod get -u` to resolve the usage of an outdated version of Font Awesome from the "hugo-modules" repository.
- Replaced the Twitter icon with the X icon in the footer to reflect the platform's rebranding.
- Verified that the icon displays correctly across all relevant pages.

### Related issue(s)

Fixes #233

image

### CODE REVIEW

**Review by yada — COMMENTED** [review]
Tested locally and LGTM, thank you.
But please sign your commit first, DCO must pass as it is a requirement for CNCF project.

**Comment by yada** [comment]
@ericklasluisa  
Waiting for DCO check to pass and will merge asap

**Comment by ericklasluisa** [comment]
Hi, I have amended the commit and signed it according to the DCO requirements.
The DCO check has now passed successfully.

The Netlify checks are still in progress. Please let me know if there's anything else I should address.

Thank you!

**Comment by yada** [comment]
Perfect thank you @ericklasluisa

**Review by yada — APPROVED** [review]
LGTM

**Pull request merged**
