### PR TITLE
update twitter to x on community page

### PR DESCRIPTION
**Pull request by mchen610**
### Description

- ...
- ...
- ...

### CODE REVIEW

**Review by yada — COMMENTED** [review]
LGTM with thanks.
But please sign your commit first, DCO must pass as it is a requirement for CNCF project.

**Comment by yada** [comment]
@mchen610 
Waiting for DCO check to pass and will merge asap

**Comment by yada** [comment]
@mchen610 "There are 2 commits incorrectly signed off. This means that the author(s) of these commits failed to include a Signed-off-by line in their commit message." please see: https://github.com/microcks/microcks.io/pull/237/checks

For information on how to fix this.

**Comment by mchen610** [comment]
@yada I tried it again, I'm not sure if it worked. I added the -s tag.

**Comment by yada** [comment]
@mchen610 the DCO check failed, you need to git rebase (all the infos are in "Details", click on it and follow the instructions):
Capture d’écran 2024-10-05 à 13 23 09

For your next PR (will be easier), add this to your .gitconfig file:
`[commit]
        template = /Users/you home directory/.stCommitMsg
        gpgsign = false`

And your sig + email in  /Users/you home directory/.stCommitMsg like:
`Signed-off-by: Firstname Lastname <myemail@domain.com>`

So, using the "git commit -sm" command will add your sig to each commit message.

**Comment by yada** [comment]
@mchen610 Can you please finish this and to be able to merge it?
Thank you

**Pull request closed without merging**
